// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOA8b86nOxVcjCbEkn_EkU6ZGv6wfB2U',
    appId: '1:392838010448:ios:d78a8f40787ff43b62a355',
    messagingSenderId: '392838010448',
    projectId: 'mentora-b835c',
    storageBucket: 'mentora-b835c.firebasestorage.app',
    iosBundleId: 'com.example.ostomyTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOA8b86nOxVcjCbEkn_EkU6ZGv6wfB2U',
    appId: '1:392838010448:ios:d78a8f40787ff43b62a355',
    messagingSenderId: '392838010448',
    projectId: 'mentora-b835c',
    storageBucket: 'mentora-b835c.firebasestorage.app',
    iosBundleId: 'com.example.ostomyTrainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC_Ir_2kFqVNV6ka_njVOXcCH56BBcFQc',
    appId: '1:392838010448:web:6f522518f741db3b62a355',
    messagingSenderId: '392838010448',
    projectId: 'mentora-b835c',
    authDomain: 'mentora-b835c.firebaseapp.com',
    storageBucket: 'mentora-b835c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_Ir_2kFqVNV6ka_njVOXcCH56BBcFQc',
    appId: '1:392838010448:web:29baaad5072aa19462a355',
    messagingSenderId: '392838010448',
    projectId: 'mentora-b835c',
    authDomain: 'mentora-b835c.firebaseapp.com',
    storageBucket: 'mentora-b835c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfgPTJFALTcdFCeCuoOPYAnLOw9A1jb8',
    appId: '1:392838010448:android:816eaf05cb4bc94962a355',
    messagingSenderId: '392838010448',
    projectId: 'mentora-b835c',
    storageBucket: 'mentora-b835c.firebasestorage.app',
  );

}